//HintName: BuildRForAttribute.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace ObjectBuildR
{
    [AttributeUsage(AttributeTargets.Class)]
    partial class BuildRForAttribute : Attribute
    {
        public BuildRForAttribute(Type type)
        {
            Type = type;
        }

        public System.Type Type { get; }
    }
}
