//HintName: BuildRBase.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace ObjectBuildR
{
    public abstract partial class BuildRBase<T>
        where T : class
    {
        protected Lazy<T> Object { get; set; }

        public abstract T Build();

        public BuildRBase<T> WithObject(T value)
        {
            Object = new System.Lazy<T>(value);
            return this;
        }
    }
}
