//HintName: UserBuilder.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using ObjectBuildR;
using ObjectBuildR.Generator.Tests.Models;
using Testing;

namespace Testing
{
    public partial class UserBuilder : BuildRBase<User>
    {
        public Lazy<string> FirstName =
            new Lazy<string>(() => default(string));
        public Lazy<string> LastName =
            new Lazy<string>(() => default(string));

        public UserBuilder WithFirstName(Func<string> func)
        {
            FirstName = new Lazy<string>(func);
            return this;
        }

        public UserBuilder WithFirstName(string value)
        {
            return WithFirstName(() => value);
        }

        public UserBuilder WithLastName(Func<string> func)
        {
            LastName = new Lazy<string>(func);
            return this;
        }

        public UserBuilder WithLastName(string value)
        {
            return WithLastName(() => value);
        }

        public override User Build()
        {
            if (Object?.IsValueCreated != true)
            {
                Object = new(() =>
                {
                    var result = new User
                    {
                        FirstName = FirstName.Value,
                        LastName = LastName.Value,
                    }
                    ;
                    return result;
                }
                );
            }
            return Object.Value;
        }
    }
}
